name: Publish Package To Multi Registry

on:
  workflow_dispatch:

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  publish-to-multi-registry:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"

      - name: Install ci and dotenvrtdb package
        run: |
          npm ci
          npm install -g github:@tolaptrinhdh61-spec/dotenvrtdb

      - name: Publish to multi-registry
        run: |
          dotenvrtdb -eUrl '${{ secrets.DOTENVRTDB_URL }}' -- node ./bin/cli.js publish
